# Generated by Django 5.2.5 on 2025-11-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_examplesentence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="parts_of_speech",
            field=models.CharField(max_length=255),
        ),
    ]
